### ISSUE TITLE
any chance for an simple example with pictures in documentaion

### ISSUE THREAD

**Issue by posuch** [TiggyWiggler/zabbix-map#1]
Just an idea - sometimes one pictures is worth thousands words - something like a simple scenario - with some IP, how to use it and output - screenshot of Zabbix map.

**Comment by TiggyWiggler** [comment]
Good idea and will definately do that in the coming days.

**Comment by TiggyWiggler** [comment]
I have now updated the Wiki with a longer description for each control parameter and included screen shots taken from worked examples.
